name: Build APK
on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Setup Android environment
        run: |
          ANDROID_HOME="$HOME/android-sdk"
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          mkdir -p "$ANDROID_HOME/cmdline-tools/latest"

      - name: Install Command-line Tools
        run: |
          cd "$ANDROID_HOME"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip -q commandlinetools-linux-*_latest.zip -d cmdline-tools/latest
          rm commandlinetools-linux-*_latest.zip
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Accept licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Install Android tools
        run: |
          sdkmanager "platform-tools" "build-tools;34.0.0"
          sdkmanager "platforms;android-34"
          sdkmanager "ndk;25.2.9519653"

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            zlib1g-dev \
            autoconf \
            libtool \
            pkg-config \
            git \
            unzip \
            adb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install --user buildozer==1.5.0 cython==0.29.36
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Clean build
        run: buildozer -v android clean  # Исправлено: bulldozer -> buildozer

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
          retention-days: 1
