name: Build APK
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            zlib1g-dev \
            autoconf \
            libtool \
            pkg-config \
            git \
            unzip \
            android-sdk \
            adb

      - name: Setup Android environment
        run: |
          echo "ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Accept Android licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Build tools
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "build-tools;34.0.0" \
            "platform-tools" \
            "platforms;android-34" \
            "ndk;25.2.9519653"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install buildozer==1.5.0
          pip install cython==0.29.36

      - name: Build APK
        run: |
          buildozer -v android clean
          buildozer -v android debug
        env:
          ACCEPT_LICENSE: "android-sdk-license.*"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            bin/*.apk
            bin/*.aab
          retention-days: 1
